services:
  letsencrypt:
    image: docker.io/adferrand/dnsrobocert:3.25.0
    container_name: sandhole_dnsrobocert
    volumes:
      - ./letsencrypt:/etc/letsencrypt
      - ./le-config.yml:/etc/dnsrobocert/config.yml:ro
    restart: unless-stopped

  sandhole:
    image: docker.io/epiceric/sandhole:latest
    container_name: sandhole
    volumes:
      - ./deploy:/deploy
      - ./letsencrypt:/letsencrypt:ro
      # Change this to where the CA certificates are on the host
      - /etc/ssl/certs:/etc/ssl/certs:ro
    # See also: https://epiceric.github.io/sandhole/cli.html
    # Make sure to change at least --domain and --acme-contact-email below
    command: |
      --domain=server.com
      --acme-contact-email=admin@server.com
      --user-keys-directory=/deploy/user_keys/
      --admin-keys-directory=/deploy/admin_keys/
      --certificates-directory=/letsencrypt/live/
      --acme-cache-directory=/deploy/acme_cache/
      --private-key-file=/deploy/server_keys/ssh
      --ssh-port=2222
      --http-port=80
      --https-port=443
      --force-https
    network_mode: host
    restart: unless-stopped
