# See https://dnsrobocert.readthedocs.io/en/latest/user_guide.html

# 1. Change this to your e-mail address
acme:
  email_account: admin@sandhole.com

# 2. Change this from sandhole.com to your domain
certificates:
  - domains:
      - sandhole.com
      - "*.sandhole.com"
    name: sandhole.com
    profile: hetzner

# 3. Configure your DNS provider.
profiles:
  - name: hetzner
    provider: hetzner
    provider_options:
      auth_token: "" # Add PAT for Hetzner
