services:
  letsencrypt:
    image: docker.io/adferrand/dnsrobocert:3.25.0
    container_name: sandhole_dnsrobocert
    restart: unless-stopped
    volumes:
      - ./letsencrypt:/etc/letsencrypt:rw
      - ./le-config.yml:/etc/dnsrobocert/config.yml:ro

  sandhole:
    image: docker.io/epiceric/sandhole:latest
    container_name: sandhole
    restart: unless-stopped
    volumes:
      - ./deploy:/deploy:rw
      - ./letsencrypt:/letsencrypt:ro
    network_mode: host
    # See also: https://sandhole.eric.dev.br/cli.html
    # Make sure to change at least --domain and --acme-contact-email below
    command: |
      --domain=sandhole.com.br
      --acme-contact-email=admin@sandhole.com.br
      --user-keys-directory=/deploy/user_keys/
      --admin-keys-directory=/deploy/admin_keys/
      --certificates-directory=/letsencrypt/live/
      --acme-cache-directory=/deploy/acme_cache/
      --private-key-file=/deploy/server_keys/ssh
      --ssh-port=2222
      --http-port=80
      --https-port=443
      --force-https
