# See https://adferrand.github.io/dnsrobocert/user_guide.html

# 1. Change this to your e-mail address
acme:
  email_account: admin@sandhole.com.br

# 2. Change these from sandhole.com.br to your domain
certificates:
  - domains:
      - sandhole.com.br
      - "*.sandhole.com.br"
    name: sandhole.com.br
    profile: hetzner

# 3. Configure your DNS provider.
profiles:
  - name: hetzner
    provider: hetzner
    provider_options:
      auth_token: "" # Add PAT for Hetzner
