# sandhole: Expose HTTP/SSH/TCP services through SSH port forwarding
# Copyright (C) 2024-2026 Eric Rodrigues Pires
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU Affero General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for
# more details.
#
# You should have received a copy of the GNU Affero General Public License along
# with this program. If not, see <https://www.gnu.org/licenses/>.

networks:
  sandhole_example:
    external: false

services:
  nginx:
    image: docker.io/nginx:alpine
    container_name: sandhole_example_nginx
    restart: unless-stopped
    networks:
      - sandhole_example

  autossh:
    image: docker.io/epiceric/sandhole-client:latest
    build:
      context: .
    container_name: sandhole_example_autossh
    restart: unless-stopped
    # Add your secret key to ./ssh_secret/id_ed25519
    volumes:
      - ./ssh_secret:/secret:ro
    networks:
      - sandhole_example
    # Make sure to change at least the Sandhole domain below
    command: |
      -i /secret/id_ed25519
      -p 2222
      -o StrictHostKeyChecking=accept-new
      -o ServerAliveInterval=30
      -R example:80:nginx:80
      sandhole.com.br
