[book]
authors = ["Eric Rodrigues Pires <eric@eric.dev.br>"]
language = "en"
multilingual = false
src = "src"
title = "The Sandhole Book"

[output.html]
git-repository-url = "https://github.com/EpicEric/sandhole"
