networks:
  sandhole-book:
    external: false

services:
  nginx:
    image: docker.io/nginx:1.29.0-alpine3.22
    container_name: sandhole_book
    restart: unless-stopped
    networks:
      - sandhole-book
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    volumes:
      - ./book:/static:ro
      - ./nginx.vh.default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

  autossh:
    image: docker.io/epiceric/sandhole-client:latest
    restart: unless-stopped
    container_name: sandhole_book_autossh
    volumes:
      - ./ssh_secret:/secret
    networks:
      - sandhole-book
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    command: |
      -i /secret/id_ed25519
      -c aes256-gcm@openssh.com
      -o StrictHostKeyChecking=accept-new
      -o ServerAliveInterval=30
      -R sandhole.com.br:80:nginx:80
      -R www.sandhole.com.br:80:nginx:80
      sandhole.com.br
      http2
