name: ci

on:
  push:
    branches: ["main"]
    tags: ["v*.*.*"]

jobs:
  docker:
    environment: Docker Build
    runs-on: ubuntu-22.04
    steps:
      - name: Collect Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ vars.DOCKERHUB_USERNAME }}/sandhole
          tags: |
            type=ref,event=branch
            type=sha,prefix=,suffix=
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PUSH_TOKEN  }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: Dockerfile.ci
          push: true
          platforms: |
            linux/amd64
            linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
