on:
  push:
    branches: ["main"]
  pull_request:

permissions:
  contents: read

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-book:
    name: Build book
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: Install Nix
        uses: NixOS/nix-installer-action@62c1943b776c509394b550f3f983adc14e9212d6 # v1.0.0
        with:
          add-channel: "true"
      - name: Build with mdBook
        run: |
          nix-build ./nix -A packages._book
      - name: Install rsync
        run: |
          nix-env -iA rsync -f '<nixpkgs>'
      - name: Deploy to Sandhole
        if: github.ref == 'refs/heads/main'
        run: |
          echo "${{ secrets.BOOK_SSH_KEY }}" > /tmp/ssh-key
          chmod 600 /tmp/ssh-key
          rsync \
            --delete-after \
            -acPe 'ssh -p ${{ secrets.BOOK_SSH_PORT }} -i /tmp/ssh-key -o StrictHostKeyChecking=accept-new' \
            result/ \
            ${{ secrets.BOOK_SSH_USER }}@${{ secrets.BOOK_SSH_HOST }}:${{ secrets.BOOK_SSH_TARGET }}
